# Config file for Segmenter

## MPI Settings
numProcesses = 8

sourcePath = /home/tim/Documents/Arbeit/TestData/20260422-2051

mode = Mode::BACKGROUND_CORRECTION_AND_COMPRESSION
# mode = Mode::OBJECT_EXTRACTION

targetPath = /home/tim/Documents/Arbeit/pisco_segmenter_cpp/Results/

allowedImageFileExtensions = .png, .jpg, .jpeg, .tiff, .tif

imageStackSize = 20
colorImage = false
maxMergeIterations = 20

normalizeImages = false
resizeImageToSpecifiedSize = true
imageSizeX = 2560
imageSizeY = 2560
skipFirstNImages = 50
skipLastNImages = 50

threshold = 10
minContourArea = 10
boundingBoxPadding = 10
